// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq0WfmX1Ejo18K4PalIltqKbetky5d9Yg',
    appId: '1:1080617629600:web:aa7acb9477cb35871556c5',
    messagingSenderId: '1080617629600',
    projectId: 'flutter-pinjam-ruang',
    authDomain: 'flutter-pinjam-ruang.firebaseapp.com',
    storageBucket: 'flutter-pinjam-ruang.appspot.com',
    measurementId: 'G-49NMK55WHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQk391ARMAofymW7W5RUUy8CFw-5z8HyM',
    appId: '1:1080617629600:android:155d6d02d04d6a7e1556c5',
    messagingSenderId: '1080617629600',
    projectId: 'flutter-pinjam-ruang',
    storageBucket: 'flutter-pinjam-ruang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWsKYlrPZtIWyWIwckgWGE4xFbwiLeU3Q',
    appId: '1:1080617629600:ios:40c212621e56ef831556c5',
    messagingSenderId: '1080617629600',
    projectId: 'flutter-pinjam-ruang',
    storageBucket: 'flutter-pinjam-ruang.appspot.com',
    iosBundleId: 'com.teknokrat.flutterPinjamRuang',
  );
}
